-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.doacoes
(
    id serial NOT NULL,
    id_usuario integer,
    descricao character varying(300) COLLATE pg_catalog."default",
    data_enviado date,
    destino_cep character varying(20) COLLATE pg_catalog."default",
    destino_rua character varying(500) COLLATE pg_catalog."default",
    destino_numero character varying(20) COLLATE pg_catalog."default",
    destino_complemento character varying(500) COLLATE pg_catalog."default",
    destino_bairro character varying(255) COLLATE pg_catalog."default",
    destino_cidade character varying(255) COLLATE pg_catalog."default",
    destino_estado character varying(255) COLLATE pg_catalog."default",
    origem_cidade character varying(255) COLLATE pg_catalog."default",
    origem_estado character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT doacoes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estatisticas
(
    id serial NOT NULL,
    data_hora timestamp without time zone,
    destino_cidade character varying(255) COLLATE pg_catalog."default",
    origem_cidade character varying(255) COLLATE pg_catalog."default",
    origem_estado character varying(255) COLLATE pg_catalog."default",
    destino_estado character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT estatisticas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.midias
(
    id serial NOT NULL,
    pacote_id integer,
    tipo character varying(50) COLLATE pg_catalog."default",
    data_upload timestamp without time zone,
    imagem bytea,
    CONSTRAINT midias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pacotes
(
    id serial NOT NULL,
    doacao_id integer,
    qrcode bytea,
    status character varying(255) COLLATE pg_catalog."default",
    data_status timestamp without time zone,
    destino_cidade character varying(255) COLLATE pg_catalog."default",
    origem_cidade character varying(255) COLLATE pg_catalog."default",
    destino_estado character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT pacotes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rastreamento
(
    id serial NOT NULL,
    pacote_id integer,
    localizacao character varying(255) COLLATE pg_catalog."default",
    data_hora timestamp without time zone,
    evento character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT rastreamento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id serial NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_usuario integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.doacoes
    ADD CONSTRAINT doacoes_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.midias
    ADD CONSTRAINT midias_pacote_id_fkey FOREIGN KEY (pacote_id)
    REFERENCES public.pacotes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pacotes
    ADD CONSTRAINT pacotes_doacao_id_fkey FOREIGN KEY (doacao_id)
    REFERENCES public.doacoes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rastreamento
    ADD CONSTRAINT rastreamento_pacote_id_fkey FOREIGN KEY (pacote_id)
    REFERENCES public.pacotes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;